databases:
  - name: contacts-db
    plan: free

services:
  - type: web
    name: flask-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirement.txt
    startCommand: |
      flask --app backend.main db upgrade && \
      gunicorn main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: contacts-db
          property: connectionString
